name: Build image

on:
    push:
        branches:
            - master
        tags-ignore:
            - '*'

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.   }}
            - name: Build
              run: |
                  docker build -f Dockerfile -t reqover/reqover:latest .
            - name: Push
              run: |
                  docker push reqover/reqover:latest
            - name: Tag image
              run: |
                  docker tag reqover/reqover:latest reqover/reqover:${GITHUB_SHA::8}
            - name: Push tagged
              run: |
                  docker push reqover/reqover:${GITHUB_SHA::8}
